version: 2
defaults: &defaults
  working_directory: /go/src/github.com/yagi5/msmini-proto

golang: &golang
  <<: *defaults
  docker:
    - image: golang
      environment:
        TZ: Asia/Tokyo

jobs:
  gen:
    <<: *golang
    steps:
      - checkout
      - run:
          name: Generage gRPC code and push
          command: |
            apt update && apt install unzip
            PROTOC_ZIP=protoc-3.3.0-linux-x86_64.zip
            curl -OL https://github.com/google/protobuf/releases/download/v3.3.0/$PROTOC_ZIP
            unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
            rm -f $PROTOC_ZIP
            make gen
            git config --global user.email ygnmhdtt@gmail.com
            git config --global user.name Hidetatsu Yaginuma 
            git add client
            git commit client -m "generate [ci skip]"
            git pull git@github.com:yagi5/msmini-proto.git master
            git push git@github.com:yagi5/msmini-proto.git master

filters: &filters
  filters:
    branches:
      only: /master/
    tags:
      only: /.*/

workflows:
  version: 2
  build-and-test:
    jobs:
      - gen:
          <<: *filters
