// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/item/item.proto

package itemv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchByNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchByNameRequest) Reset()         { *m = SearchByNameRequest{} }
func (m *SearchByNameRequest) String() string { return proto.CompactTextString(m) }
func (*SearchByNameRequest) ProtoMessage()    {}
func (*SearchByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3860422cb749b9c, []int{0}
}

func (m *SearchByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchByNameRequest.Unmarshal(m, b)
}
func (m *SearchByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchByNameRequest.Marshal(b, m, deterministic)
}
func (m *SearchByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchByNameRequest.Merge(m, src)
}
func (m *SearchByNameRequest) XXX_Size() int {
	return xxx_messageInfo_SearchByNameRequest.Size(m)
}
func (m *SearchByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchByNameRequest proto.InternalMessageInfo

func (m *SearchByNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SearchByNameResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchByNameResponse) Reset()         { *m = SearchByNameResponse{} }
func (m *SearchByNameResponse) String() string { return proto.CompactTextString(m) }
func (*SearchByNameResponse) ProtoMessage()    {}
func (*SearchByNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3860422cb749b9c, []int{1}
}

func (m *SearchByNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchByNameResponse.Unmarshal(m, b)
}
func (m *SearchByNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchByNameResponse.Marshal(b, m, deterministic)
}
func (m *SearchByNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchByNameResponse.Merge(m, src)
}
func (m *SearchByNameResponse) XXX_Size() int {
	return xxx_messageInfo_SearchByNameResponse.Size(m)
}
func (m *SearchByNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchByNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchByNameResponse proto.InternalMessageInfo

func (m *SearchByNameResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                int64                `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Category             string               `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3860422cb749b9c, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Item) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Item) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchByNameRequest)(nil), "itemv1.SearchByNameRequest")
	proto.RegisterType((*SearchByNameResponse)(nil), "itemv1.SearchByNameResponse")
	proto.RegisterType((*Item)(nil), "itemv1.Item")
}

func init() { proto.RegisterFile("proto/item/item.proto", fileDescriptor_b3860422cb749b9c) }

var fileDescriptor_b3860422cb749b9c = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x3f, 0x4f, 0xfb, 0x30,
	0x14, 0x54, 0xfa, 0xef, 0xf7, 0xeb, 0x4b, 0xc5, 0x60, 0x8a, 0x14, 0x05, 0x24, 0xa2, 0x4c, 0x61,
	0x49, 0x45, 0x99, 0x60, 0x2b, 0x5b, 0x17, 0x86, 0x94, 0x81, 0x0d, 0xb9, 0xc9, 0xa3, 0x58, 0xc2,
	0xb5, 0xb1, 0x5f, 0x2b, 0xf5, 0x7b, 0xf3, 0x01, 0x90, 0xed, 0xa6, 0x14, 0xa9, 0x12, 0x4b, 0xf4,
	0xee, 0xdd, 0x5d, 0xce, 0x3e, 0xc3, 0x85, 0x36, 0x8a, 0xd4, 0x44, 0x10, 0x4a, 0xff, 0x29, 0x3d,
	0x66, 0x03, 0x37, 0x6f, 0x6f, 0xd3, 0xeb, 0x95, 0x52, 0xab, 0x0f, 0x9c, 0xf8, 0xed, 0x72, 0xf3,
	0x36, 0x21, 0x21, 0xd1, 0x12, 0x97, 0x3a, 0x08, 0xf3, 0x1b, 0x38, 0x5f, 0x20, 0x37, 0xf5, 0xfb,
	0xe3, 0xee, 0x89, 0x4b, 0xac, 0xf0, 0x73, 0x83, 0x96, 0x18, 0x83, 0xde, 0x9a, 0x4b, 0x4c, 0xa2,
	0x2c, 0x2a, 0x86, 0x95, 0x9f, 0xf3, 0x07, 0x18, 0xff, 0x96, 0x5a, 0xad, 0xd6, 0x16, 0x59, 0x0e,
	0x7d, 0x97, 0x66, 0x93, 0x28, 0xeb, 0x16, 0xf1, 0x74, 0x54, 0x86, 0xec, 0x72, 0x4e, 0x28, 0xab,
	0x40, 0xe5, 0x5f, 0x11, 0xf4, 0x1c, 0x66, 0x67, 0xd0, 0x11, 0xcd, 0xfe, 0xb7, 0x1d, 0xd1, 0x1c,
	0x82, 0x3a, 0x3f, 0x41, 0x2c, 0x83, 0xb8, 0x41, 0x5b, 0x1b, 0xa1, 0x49, 0xa8, 0x75, 0xd2, 0xf5,
	0xd4, 0xf1, 0x8a, 0x8d, 0xa1, 0xaf, 0x8d, 0xa8, 0x31, 0xe9, 0x65, 0x51, 0xd1, 0xad, 0x02, 0x60,
	0x29, 0xfc, 0xaf, 0x39, 0xe1, 0x4a, 0x99, 0x5d, 0xd2, 0xf7, 0xa6, 0x03, 0x66, 0xf7, 0x00, 0xb5,
	0x41, 0x4e, 0xd8, 0xbc, 0x72, 0x4a, 0x06, 0x59, 0x54, 0xc4, 0xd3, 0xb4, 0x0c, 0xed, 0x94, 0x6d,
	0x3b, 0xe5, 0x73, 0xdb, 0x4e, 0x35, 0xdc, 0xab, 0x67, 0xe4, 0xac, 0x1b, 0xdd, 0xb4, 0xd6, 0x7f,
	0x7f, 0x5b, 0xf7, 0xea, 0x19, 0x4d, 0x5f, 0x20, 0x76, 0xb7, 0x5e, 0xa0, 0xd9, 0xba, 0x03, 0xce,
	0x61, 0x74, 0xdc, 0x20, 0xbb, 0x6c, 0xab, 0x3a, 0xf1, 0x04, 0xe9, 0xd5, 0x69, 0x32, 0x94, 0xbe,
	0x1c, 0xf8, 0xe0, 0xbb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x98, 0x4e, 0x41, 0x00, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemServiceClient interface {
	SearchByName(ctx context.Context, in *SearchByNameRequest, opts ...grpc.CallOption) (*SearchByNameResponse, error)
}

type itemServiceClient struct {
	cc *grpc.ClientConn
}

func NewItemServiceClient(cc *grpc.ClientConn) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) SearchByName(ctx context.Context, in *SearchByNameRequest, opts ...grpc.CallOption) (*SearchByNameResponse, error) {
	out := new(SearchByNameResponse)
	err := c.cc.Invoke(ctx, "/itemv1.ItemService/SearchByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
type ItemServiceServer interface {
	SearchByName(context.Context, *SearchByNameRequest) (*SearchByNameResponse, error)
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_SearchByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).SearchByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/itemv1.ItemService/SearchByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).SearchByName(ctx, req.(*SearchByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "itemv1.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchByName",
			Handler:    _ItemService_SearchByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/item/item.proto",
}
